### ISSUE TITLE
Working with Fastboot

### ISSUE THREAD

**Issue by chrism** [stonecircle/broccoli-static-site-json#12]
Hi,

I've managed to get this working nicely on a simple test site now and hosted on S3
https://github.com/chrism/test-static-json
http://test-static-json.s3-website.eu-west-3.amazonaws.com/

So now I'm trying to add Prember too—as I've read how you've adopted that for the guides documentation and think that would be a great addition.

The issue is that I'm now getting  a 404 error for the JSON request when running `ember s` with the prember flag set to true.

Fastboot alone seems to work fine, and I assume it is something to do with serving the JSON responses during the Prember build.

Digging around the issues of Prember I see you've done some work on this, with
https://github.com/ef4/prember/pull/15

But I still haven't really been able to understand how to get this to work, or if it even should be working.

Maybe this is more a documentation issue but some guidance would be appreciated and I'd be happy to contribute to the docs once it's working.

Thanks :)

**Comment by mansona** [comment]
hey @chrism 👋 

Yes it's a bit of a complicated issue all around 🤔 what are you using to **get** the json? is it using Ember Data? or is it using fetch?

**Comment by chrism** [comment]
Hi @mansona :)

Oh no! I was hoping that wasn’t the case :(

I’m using ember data and just customizing the adapter slightly for the correct paths.

**Comment by chrism** [comment]
Hi again 👋

Thanks, yes—I took a look at those adapter changes, but for my use cases adopted to alter the `urlForFindAll` and `urlForFindRecord` methods like this:

```js
import DS from 'ember-data';
import config from '../config/environment';

export default DS.JSONAPIAdapter.extend({
  host: config.rootURL,
  namespace: 'api/v1',

  urlForFindAll(modelName) {
    const path = this.pathForType(modelName);
    return `${this.host}${this.namespace}/${path}/all-${path}.json`;
  },

  urlForFindRecord(id, modelName) {
    const path = this.pathForType(modelName);
    return `${this.host}${this.namespace}/${path}/${id}.json`;
  }
});
```
https://github.com/chrism/test-static-json/blob/prember/app/adapters/application.js

I felt like that was a little easier for me to rationalise. Maybe I am missing something by doing this?
https://github.com/chrism/test-static-json/tree/prember

I've added a branch called `prember` where you can see the site working fine with fastboot by running

`ember serve`

But which blows up if you run

`PREMBER=true ember serve`

```
Error while processing route: index Ember Data Request GET /api/v1/projects/all-projects.json returned a 404
Payload (Empty Content-Type)
...
```

note: for now I'm only trying to pre-render the home screen—I was going to tackle crawling the content once that is working.

Having said this I'd love to get it working because for me this could really be the ideal approach to building modern static sites. I'm sure you get this already, but this is the vision I have in mind...

My ideal would be to host everything on S3 using `ember-deploy` pipeline and index strategy.

By not requiring any external API hosting, and instead including the content simply as flat .json files (by using this plugin) it keeps this whole process self-contained.

The fact that these same files can also be used to pre-render with Prember and Fastboot is perfect and means that the initial load time will be like a static site.

From that point I want to focus on the rehyrdation/effective transition from a flat site with only anchor tags working to a fully interactive rich web application.

For me, coming from a more visual side that's what really excites me—the prospect of a fast loading site, but which can then seamless transition in to a fluid, modern experience.

I feel like this is the last piece of the puzzle that I'm struggling with.

Maybe from this plugin, it could be wrapped to make it a little higher level with a kind of meta 'blueprint for making blueprints', customised adapter and packaged as a clean solution for building static sites.

Anyway, just sharing my thoughts—would be happy to help move this forward if you have a similar goal in mind.

Any help on implementing an adapter which can resolve this would be really appreciated. I already have a blog post on how to do this mind, at the very least.

**Comment by chrism** [comment]
Hi again 👋 

Sorry to bother you again on this but I'm just coming back to it (personal project, for now) and still struggling to avoid the dreaded 404 error.

Here is my latest version on a prember branch.
https://github.com/chrism/test-static-json/tree/prember

I've looked at your approach to the adapter in the `guides-app` and tried to replicate it exactly to ensure there aren't some path differences between them.

This is my adapter now for the model hook.

```js
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
  urlForFindAll(modelName) {
    const path = this.pathForType(modelName);
    let url = ['api', 'v1', path, `all-${path}.json`];

    let host = this.host;
    let prefix = this.urlPrefix();

    if (prefix) { url.unshift(prefix); }

    url = url.join('/');
    if (!host && url && url.charAt(0) !== '/') {
      url = '/' + url;
    }

    console.log({ host });
    console.log({ prefix });
    console.log({ url });
    return url;
  }
});
```

I've also logged the same variables running `PREMBER=true ember s` using the guides-app.

Although the variables are the same, while the guides app works I'm still getting this same error message.

```
DEBUG: -------------------------------
DEBUG: Ember      : 3.4.5
DEBUG: Ember Data : 3.4.4
DEBUG: -------------------------------
{ host: undefined }
{ prefix: '' }
{ url: '/api/v1/projects/all-projects.json' }
Error while processing route: index Ember Data Request GET /api/v1/projects/all-projects.json returned a 404
Payload (Empty Content-Type)
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v1/projects/all-projects.json</pre>
</body>
</html>
 Error: Ember Data Request GET /api/v1/projects/all-projects.json returned a 404
Payload (Empty Content-Type)
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v1/projects/all-projects.json</pre>
</body>
</html>

    at ErrorClass.EmberError (/Users/chrismasters/git/test-static-json/tmp/prember-input_base_path-hksJ5Hwr.tmp/assets/@ember/error/index.js:37:1)
    at ErrorClass.AdapterError (/Users/chrismasters/git/test-static-json/tmp/prember-input_base_path-hksJ5Hwr.tmp/assets/addon-tree-output/ember-data/-private.js:3340:1)
    at new ErrorClass (/Users/chrismasters/git/test-static-json/tmp/prember-input_base_path-hksJ5Hwr.tmp/assets/addon-tree-output/ember-data/-private.js:3358:1)
    at Class.handleResponse (/Users/chrismasters/git/test-static-json/tmp/prember-input_base_path-hksJ5Hwr.tmp/assets/addon-tree-output/ember-data/adapters/rest.js:804:1)
    at ajaxError (/Users/chrismasters/git/test-static-json/tmp/prember-input_base_path-hksJ5Hwr.tmp/assets/addon-tree-output/ember-data/adapters/rest.js:1084:1)
    at ajaxErrorHandler (/Users/chrismasters/git/test-static-json/tmp/prember-input_base_path-hksJ5Hwr.tmp/assets/addon-tree-output/ember-data/adapters/rest.js:1111:1)
    at Object.hash.error (/Users/chrismasters/git/test-static-json/tmp/prember-input_base_path-hksJ5Hwr.tmp/assets/addon-tree-output/ember-data/adapters/rest.js:879:1)
    at fire (/Users/chrismasters/git/test-static-json/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.fireWith (/Users/chrismasters/git/test-static-json/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.fire [as reject] (/Users/chrismasters/git/test-static-json/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at onError (/Users/chrismasters/git/test-static-json/node_modules/najax/lib/najax.js:208:9)
    at dataHandler (/Users/chrismasters/git/test-static-json/node_modules/najax/lib/najax.js:153:18)
    at IncomingMessage.<anonymous> (/Users/chrismasters/git/test-static-json/node_modules/najax/lib/najax.js:198:9)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
pre-render / failed with exception: Error: Ember Data Request GET /api/v1/projects/all-projects.json returned a 404
Payload (Empty Content-Type)
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v1/projects/all-projects.json</pre>
</body>
</html>

Build Error (prember)

Some pre-rendered URLs had failures
```

If I use `ember s` it works fine (with Fastboot).

If I use `FASTBOOT_DISABLED=true ember s` it works fine too (without Fastboot).

If I try to hit the url logged in the browser that also returns the JSON correctly.

Any suggestions for finding a way round this gratefully appreciated... I'm kind of stuck.

Many thanks!

**Comment by mansona** [comment]
So as it turns out this has nothing to do with the actual adapter 😖 I ended up putting a debugger in the prember addon so that I could get a look at the folder on disk where the generated files were supposed to be and your json files were **not** there 😫 

It turns out that something I thought was optional in our Guides App setup is absolutely not optional at all, and the way I've been using this in my other projects hid this requirement from me until now. 

You **must** create an in-repo addon to use this and you need to make sure that the in-repo addon is a **prember-plugin**. You can see a tiny bit more information here https://github.com/ef4/prember#using-prember-from-an-addon but essentially it boils down to the fact that the prember system can only see your app tree at the time of building and returning a Merged Tree doesn't actually fix this.

If you do `ember generate in-repo-addon` and add `prember-plugin` to the package.json just under `ember-addon` then you can make your index.js look like this: 

```
/* eslint-env node */
'use strict';

const StaticSiteJson = require('broccoli-static-site-json');

const projectTree = new StaticSiteJson('content/projects', {
  type: 'project',
  contentFolder: 'api/v1/projects',
  attributes: [
    'title',
    'createdAt'
  ],
  collections: [{
    src: 'content/projects',
    output: 'all-projects.json',
  }]
});

module.exports = {
  name: require('./package').name,

  isDevelopingAddon() {
    return true;
  },

  treeForPublic() {
    return projectTree;
  }
};
```

and it should work. 

Let me know how you get on 👍

**Comment by chrism** [comment]
That was it!!

:smile: :smile: :smile:

Thank you so much, I never would have worked out by myself that it was necessary to include it as an in-app addon. Did I miss that in the documentation somewhere? If so, i'm really sorry.

I actually prefer it this way and it makes perfect sense as an in-app addon as it keeps the `ember-cli-build.js` simple and there are convenient hooks for prember URLs too at the same time, it's just not something I'd considered and is the first time I've used an in-app addon.

Thanks so much!

**Comment by mansona** [comment]
No worries 😄 I don't think you missed any documentation at all, it's something that is actually missing (I think)

I will create a follow-up issue to make sure we document it somewhere but I'm glad that you're back working away 🎉 

Let me know if you have any more issues
