### ISSUE TITLE
Document the need to use this in an in-repo addon when using Prember in an Ember app

### ISSUE THREAD

**Issue by mansona** [stonecircle/broccoli-static-site-json#13]
This is a follow-on issue from https://github.com/stonecircle/broccoli-static-site-json/issues/12

Here is a short description of the issue: 

> You **must** create an in-repo addon to use this and you need to make sure that the in-repo addon is a **prember-plugin**. You can see a tiny bit more information here https://github.com/ef4/prember#using-prember-from-an-addon but essentially it boils down to the fact that the prember system can only see your app tree at the time of building and returning a Merged Tree doesn't actually fix this.

**Comment by chrism** [comment]
hi @masona hopefully this PR should help with this

https://github.com/stonecircle/broccoli-static-site-json/pull/14

**Comment by mansona** [comment]
This is fixed now in #15 

Thanks @chrism for staring off the documentation, it is much appreciated 🎉
